  name: CI

  env:
    DOTNET_VERSION: '8.0'

  on:
    push:

  jobs:
    build:
      name: CI
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - name: Set up .NET Core
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}

        - name: Dotnet run tests
          run: dotnet test --configuration Release

        - name: Dotnet publish
          run: dotnet publish src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj --configuration Release -o artifacts

        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: dometrain-artifact
            path: artifacts/
