
name: Secrets flow

env:
  API_CSPROJ_PATH: "./src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj"

on:
  pull_request:
    branches: ["main"]

jobs:
  secrets:
    name: Secrets demo
    runs-on: ubuntu-latest
    env:
      JOB_NAME: "secrets"

    steps:
      - name: echo general environment variable
        run: echo "$API_CSPROJ_PATH"

      - name: echo local for this job environment variable
        run: echo "$JOB_NAME"

  new_job:
    name: Secrets demo
    runs-on: ubuntu-latest
    env:
      JOB_NAME: "new_job"

    steps:
      - name: echo general environment variable
        run: echo "$API_CSPROJ_PATH"

      - name: echo local for this job environment variable
        run: echo "$JOB_NAME"